[build-system]
requires = [
	 "setuptools>=42",
	 "wheel",
	 "setuptools-scm[toml]>=3.4",
	 "fastentrypoints"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/ymp/_version.py"

