import os

from ymp.config import icfg
icfg.init()

# make sure rules are executed in bash (not sh, dash or worse)
shell.executable("/bin/bash")

refname = str("({})".format("|".join(icfg.ref)))

wildcard_constraints:
    dir      = "[^/]+?",
    dir1     = "[^/]+",
    dir2     = "[^/]+",
    sample   = "[^/]+",
    file     = "[^/]+",

    nodots   = "[^/.]+",
    query    = "[^/.]+",
    gene     = "[^/.]+",

    fracid   = "[0-9][0-9]",
    coverage = "[0-9]+",
    evalue   = "[0-9]+",
    length   = "[1-9][0-9]*",

    SRR = "[EDS]RR[0-9]+",
    rnagene="({})".format("|".join(icfg.db.rrna)),
    project = "({})".format("|".join(icfg.datasets)),
    pairname = "({})".format("|".join(icfg.pairnames)),
    refname = refname,
    assembler = "(mh|mhc|sp|ref_{})".format(refname),
    mapper = "(bt2|bbm)",
    genefind = "(blast)",

    fasta = "(fasta|fna|fa)",
    fastp = "(fastp|faa)",
    fagz  = "(fasta|fna|fa)(|.gz)",
    fqgz  = "(fq)(|.gz)",

    by = "(\.by_[^./]*|)",
    target = "[^/.]+",
    source = "[^/.]+"

for fn in os.listdir(srcdir("")):
    if fn.endswith(".rules"):
        include: fn

