include: "init.rules"
include: "phony.rules"
include: "convert.rules"

include: "fastq.rules"

include: "assembly.rules"
include: "assembly_qc.rules"

include: "genepred.rules"

#include: "rrna.rules"
include: "align.rules"
include: "tree.rules"

include: "anvio.rules"

#include: "all.rules"
