import os

import ymp
from ymp.env import Env
from ymp.stage import Stage, Reference

ymp.get_config().activate()

# make sure rules are executed in bash (not sh, dash or worse)
shell.executable(ymp.get_config().shell)

wildcard_constraints:
    _YMP_DIR = r"([^/]+\.|)",

    target = r"[^/.]+",
    source = r"[^/.]+"

with Stage.new_registry() as stage, Env.new_registry() as env:
    for snakefile in ymp.get_config().snakefiles:
        include: snakefile

